#
# ğŸ›‘ Think twice before editing this file! ğŸ›‘
# âš ï¸ This file is maintained via https://github.com/IanStorm/dev-settings-sync. âš ï¸
#

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Docker ğŸ”„ï¸

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * 5' # weekly, i.e. every Friday at 10pm

jobs:
  Docker:
    uses: IanStorm/reusable-workflows/.github/workflows/_docker.yml@main
    with:
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
